package com.delivery.dvApp.entity;

import com.delivery.dvApp.enums.Vehicle;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;


/**
 * Entity representing a Courier in the delivery system.
 *
 * <p>
 * A Courier is responsible for picking up orders from restaurants
 * and delivering them to customers. This entity stores identification,
 * contact information, vehicle type, and real-time location data.
 * </p>
 *
 * <p>
 * The entity supports soft deletion using the {@code deleted} flag,
 * meaning records remain in the database even if the courier is deactivated.
 * </p>
 */
@Entity
public class Courier {

    /**
     * Unique identifier of the courier.
     * Auto-generated by the database.
     * Read-only in JSON requests.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private Long id;


    /**
     * Full name of the courier.
     */
    private String name;


    /**
     * Type of vehicle used by the courier
     * (e.g., BIKE, CAR, SCOOTER).
     *
     * Stored as a String in the database.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Vehicle vehicle;

    /**
     * Current latitude of the courier.
     * Used for tracking or proximity calculations.
     */
    private Double currentLatitude;

    /**
     * Current longitude of the courier.
     * Used for tracking or proximity calculations.
     */
    private Double currentLongitude;


    /**
     * Contact phone number of the courier.
     */
    private String phoneNumber;


    /**
     * Soft delete flag.
     *
     * <p>
     * When set to true, the courier is considered inactive
     * but remains stored in the database.
     * This field is read-only in JSON.
     * </p>
     */
    @Column(nullable = false)
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private boolean deleted = false;



    /**
     * Default constructor required by JPA.
     */
    public Courier() {
    }

    /**
     * Constructor for creating a new Courier.
     *
     * @param name             courier name
     * @param vehicle          type of vehicle used
     * @param currentLatitude  current latitude position
     * @param currentLongitude current longitude position
     * @param phoneNumber      contact phone number
     */
    public Courier(String name, Vehicle vehicle, Double currentLatitude, Double currentLongitude,String phoneNumber) {
        this.name = name;
        this.vehicle = vehicle;
        this.currentLatitude = currentLatitude;
        this.currentLongitude = currentLongitude;
        this.phoneNumber = phoneNumber;
    }

    /**
     * @return courier ID
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id courier ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return courier name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name courier name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return vehicle type
     */
    public Vehicle getVehicle() {
        return vehicle;
    }

    /**
     * @param vehicle vehicle type
     */
    public void setVehicle(Vehicle vehicle) {
        this.vehicle = vehicle;
    }

    /**
     * @return current latitude
     */
    public Double getCurrentLatitude() {
        return currentLatitude;
    }

    /**
     * @param currentLatitude current latitude
     */
    public void setCurrentLatitude(Double currentLatitude) {
        this.currentLatitude = currentLatitude;
    }

    /**
     * @return current longitude
     */
    public Double getCurrentLongitude() {
        return currentLongitude;
    }

    /**
     * @param currentLongitude current longitude
     */
    public void setCurrentLongitude(Double currentLongitude) {
        this.currentLongitude = currentLongitude;
    }

    /**
     * @return courier phone number
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * @param phoneNumber courier phone number
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * @return true if courier is soft-deleted, false otherwise
     */
    public boolean isDeleted() {
        return deleted;
    }

    /**
     * @param deleted soft delete flag
     */
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }
}
