package com.delivery.dvApp.entity;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;



/**
 * Entity representing a Customer in the system.
 *
 * <p>
 * A Customer can place multiple Orders and contains
 * basic contact and address information required
 * for delivery purposes.
 * </p>
 *
 * <p>
 * This entity supports soft deletion using the {@code deleted} flag,
 * meaning records are not physically removed from the database.
 * </p>
 */
@Entity
public class Customer {


    /**
     * Unique identifier of the customer.
     * Auto-generated by the database.
     * Read-only in JSON requests.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private Long id;

    /**
     * Full name of the customer.
     */
    private String name;

    /**
     * Delivery address of the customer.
     */
    private String address;

    /**
     * Contact phone number of the customer.
     */
    private String phoneNumber;

    /**
     * Soft delete flag.
     *
     * <p>
     * When set to true, the customer is considered deleted
     * but remains stored in the database.
     * This field is read-only in JSON.
     * </p>
     */
    @Column(nullable = false)
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private boolean deleted = false;


    /**
     * Default constructor required by JPA.
     */
    public Customer() {
    }

    /**
     * Constructor for creating a new Customer.
     *
     * @param name        customer name
     * @param address     delivery address
     * @param phoneNumber contact phone number
     */
    public Customer(String name, String address,String phoneNumber) {
        this.name = name;
        this.address = address;
        this.phoneNumber = phoneNumber;
    }

    /**
     * @return customer ID
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id customer ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return customer name
     */
    public String getName() {
        return name;
    }


    /**
     * @param name customer name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return customer address
     */
    public String getAddress() {
        return address;
    }

    /**
     * @param address customer address
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * @return customer phone number
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * @param phoneNumber customer phone number
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * @return true if customer is soft-deleted, false otherwise
     */
    public boolean isDeleted() {
        return deleted;
    }

    /**
     * @param deleted soft delete flag
     */
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }
}
