package com.delivery.dvApp.entity;


import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;


import java.math.BigDecimal;
/**
 * Entity representing a menu Item offered by a Restaurant.
 *
 * <p>
 * This entity is mapped to a database table via JPA and stores
 * information about individual food or product items that belong
 * to a specific restaurant.
 * </p>
 *
 * <p>
 * Each item is associated with one {@link Restaurant} (Many-to-One relationship).
 * The entity also supports soft deletion using the {@code deleted} flag.
 * </p>
 */
@Entity
public class Item {

    /**
     * Unique identifier of the item.
     *
     * <p>
     * Auto-generated by the database using IDENTITY strategy.
     * This field is read-only in JSON requests.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private Long id;

    /**
     * Name of the item.
     */
    private String name;

    /**
     * Detailed description of the item.
     */
    private  String description;


    /**
     * The restaurant that owns this item.
     *
     * <p>
     * Many items can belong to one restaurant.
     * A foreign key column {@code restaurant_id} is used
     * in the database.
     * </p>
     */
    @ManyToOne
    @JoinColumn(name="restaurant_id")
    private Restaurant restaurant;

    /**
     * Price of the item.
     *
     * <p>
     * BigDecimal is used instead of double to ensure
     * precision for monetary values.
     * </p>
     */
    private BigDecimal price;


    /**
     * Soft delete flag.
     *
     * <p>
     * When true, the item is considered deleted
     * but remains stored in the database.
     * This field is read-only in JSON.
     * </p>
     */
    @Column(nullable = false)
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private boolean deleted = false;



    /**
     * Default constructor required by JPA.
     */
    public Item() {
    }

    /**
     * Constructor for creating a new Item.
     *
     * @param name        item name
     * @param description item description
     * @param restaurant  associated restaurant
     * @param price       item price
     */
    public Item(String name, String description, Restaurant restaurant, BigDecimal price) {
        this.name = name;
        this.description = description;
        this.restaurant = restaurant;
        this.price = price;
    }

    /**
     * @return item ID
     */
    public Long getId() {
        return id;
    }


    /**
     * @param id item ID
     */
    public void setId(Long id) {
        this.id = id;
    }


    /**
     * @return item name
     */
    public String getName() {
        return name;
    }


    /**
     * @param name item name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return item description
     */
    public String getDescription() {
        return description;
    }


    /**
     * @param description item description
     */
    public void setDescription(String description) {
        this.description = description;
    }


    /**
     * @return associated restaurant
     */
    public Restaurant getRestaurant() {
        return restaurant;
    }


    /**
     * @param restaurant associated restaurant
     */
    public void setRestaurant(Restaurant restaurant) {
        this.restaurant = restaurant;
    }



    /**
     * @return item price
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * @param price item price
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }



    /**
     * @return true if item is soft-deleted, false otherwise
     */
    public boolean isDeleted() {
        return deleted;
    }

    /**
     * @param deleted soft delete flag
     */
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }
}
