package com.delivery.dvApp.entity;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;

import java.math.BigDecimal;

/**
 * Entity representing a single item within an Order.
 *
 * <p>
 * OrderItem acts as a bridge entity between {@link Order} and {@link Item}.
 * It stores additional information specific to the order, such as
 * quantity and price at the time of purchase.
 * </p>
 *
 * <p>
 * This design allows preserving historical pricing information even if
 * the original Item price changes later.
 * </p>
 */
@Entity
public class OrderItem {

    /**
     * Unique identifier of the order item.
     * Auto-generated by the database.
     * Read-only in JSON requests.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private Long id;

    /**
     * The order to which this item belongs.
     *
     * <p>
     * Many OrderItems can belong to one Order.
     * A foreign key column {@code order_id} is used.
     * </p>
     */
    @ManyToOne
    @JoinColumn(name = "order_id")
    private Order order;

    /**
     * The menu item being ordered.
     *
     * <p>
     * Many OrderItems can reference the same Item.
     * A foreign key column {@code item_id} is used.
     * </p>
     */
    @ManyToOne
    @JoinColumn(name = "item_id")
    private Item item;

    /**
     * Quantity of the item ordered.
     */
    private int quantity;

    /**
     * Price of the item at the time the order was placed.
     *
     * <p>
     * Stored separately to ensure historical accuracy,
     * even if the Item's current price changes later.
     * </p>
     */
    private BigDecimal priceAtPurchase;

    /**
     * Default constructor required by JPA.
     */
    public OrderItem() {
    }

    /**
     * Constructor for creating a new OrderItem.
     *
     * @param order            associated order
     * @param item             ordered item
     * @param quantity         quantity of the item
     * @param priceAtPurchase  price at the time of purchase
     */
    public OrderItem(Order order, Item item, int quantity, BigDecimal priceAtPurchase) {
        this.order = order;
        this.item = item;
        this.quantity = quantity;
        this.priceAtPurchase = priceAtPurchase;
    }

    /**
     * @return order item ID
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id order item ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return associated order
     */
    public Order getOrder() {
        return order;
    }

    /**
     * @param order associated order
     */
    public void setOrder(Order order) {
        this.order = order;
    }

    /**
     * @return associated item
     */
    public Item getItem() {
        return item;
    }

    /**
     * @param item associated item
     */
    public void setItem(Item item) {
        this.item = item;
    }

    /**
     * @return quantity of the item ordered
     */
    public int getQuantity() {
        return quantity;
    }

    /**
     * @param quantity quantity of the item ordered
     */
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    /**
     * @return price at the time of purchase
     */
    public BigDecimal getPriceAtPurchase() {
        return priceAtPurchase;
    }

    /**
     * @param priceAtPurchase price at the time of purchase
     */
    public void setPriceAtPurchase(BigDecimal priceAtPurchase) {
        this.priceAtPurchase = priceAtPurchase;
    }
}
