package com.delivery.dvApp.entity;

import com.delivery.dvApp.enums.OrderStatus;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;



/**
 * Entity representing a customer Order in the system.
 *
 * <p>
 * An Order connects a Customer, Restaurant, Courier and a collection
 * of OrderItems. It stores pricing information, current status,
 * and timestamps describing the order lifecycle.
 * </p>
 *
 * <p>
 * The lifecycle of an order is tracked using {@link OrderStatus}
 * and multiple timestamp fields (created, picked, delivered, cancelled).
 * </p>
 */
@Entity
@Table(name = "cus_order")
public class Order {


    /**
     * Unique identifier of the order.
     * Auto-generated by the database.
     * Read-only in JSON requests.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private Long id;

    /**
     * Total price of the order.
     * Calculated based on associated OrderItems.
     */
    private BigDecimal totalPrice;


    /**
     * Restaurant that prepares the order.
     * Many orders can belong to one restaurant.
     */
    @ManyToOne
    @JoinColumn(name = "restaurant_id")
    private Restaurant restaurant;


    /**
     * Customer who placed the order.
     * Many orders can belong to one customer.
     */
    @ManyToOne
    @JoinColumn(name = "customer_id")
    private Customer customer;


    /**
     * Courier responsible for delivering the order.
     * Many orders can be assigned to one courier.
     */
    @ManyToOne
    @JoinColumn(name = "courier_id")
    private Courier courier;


    /**
     * List of items included in this order.
     *
     * <p>
     * One order can contain multiple OrderItems.
     * The relationship is mapped by the "order" field
     * inside the OrderItem entity.
     * </p>
     */
    @OneToMany(mappedBy = "order")
    private List<OrderItem> orderItems;



    /**
     * Current status of the order (e.g. CREATED, ACCEPTED,
     * PICKED_UP, DELIVERED, CANCELLED).
     *
     * Stored as a String in the database.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private OrderStatus status;

    /**
     * Timestamp when the order was created.
     */
    private LocalDateTime createdAt;

    /**
     * Timestamp when the order was delivered.
     */
    private  LocalDateTime deliveredAt;

    /**
     * Timestamp when the courier picked up the order.
     */
    private LocalDateTime pickedAt;

    /**
     * Timestamp when the order was cancelled.
     */
    private LocalDateTime cancelledAt;

    /**
     * Default constructor required by JPA.
     */
    public Order() {
    }

    /**
     * Full constructor for creating an Order.
     *
     * @param totalPrice   total price of the order
     * @param restaurant   restaurant preparing the order
     * @param customer     customer who placed the order
     * @param courier      assigned courier
     * @param orderItems   list of order items
     * @param status       current order status
     * @param createdAt    creation timestamp
     * @param deliveredAt  delivery timestamp
     * @param pickedAt     pickup timestamp
     * @param cancelledAt  cancellation timestamp
     */
    public Order( BigDecimal totalPrice, Restaurant restaurant, Customer customer, Courier courier,
                  List<OrderItem> orderItems,OrderStatus status,LocalDateTime createdAt,
                  LocalDateTime deliveredAt,LocalDateTime pickedAt,LocalDateTime cancelledAt) {
        this.totalPrice = totalPrice;
        this.restaurant = restaurant;
        this.customer = customer;
        this.courier = courier;
        this.orderItems = orderItems;
        this.status = status;
        this.createdAt = createdAt;
        this.deliveredAt = deliveredAt;
        this.pickedAt = pickedAt;
        this.cancelledAt = cancelledAt;
    }

    /**
     * @return order ID
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id order ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return total price of the order
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * @param totalPrice total price of the order
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * @return restaurant associated with this order
     */
    public Restaurant getRestaurant() {
        return restaurant;
    }

    /**
     * @param restaurant restaurant associated with this order
     */
    public void setRestaurant(Restaurant restaurant) {
        this.restaurant = restaurant;
    }

    /**
     * @return customer who placed the order
     */
    public Customer getCustomer() {
        return customer;
    }

    /**
     * @param customer customer who placed the order
     */
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    /**
     * @return assigned courier
     */
    public Courier getCourier() {
        return courier;
    }

    /**
     * @param courier assigned courier
     */
    public void setCourier(Courier courier) {
        this.courier = courier;
    }

    /**
     * @return list of order items
     */
    public List<OrderItem> getOrderItems() {
        return orderItems;
    }

    /**
     * @param orderItems list of order items
     */
    public void setOrderItems(List<OrderItem> orderItems) {
        this.orderItems = orderItems;
    }


    /**
     * @return current order status
     */
    public OrderStatus getStatus() {
        return status;
    }


    /**
     * @param status current order status
     */
    public void setStatus(OrderStatus status) {
        this.status = status;
    }

    /**
     * @return creation timestamp
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * @param createdAt creation timestamp
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * @return delivery timestamp
     */
    public LocalDateTime getDeliveredAt() {
        return deliveredAt;
    }

    /**
     * @param deliveredAt delivery timestamp
     */
    public void setDeliveredAt(LocalDateTime deliveredAt) {
        this.deliveredAt = deliveredAt;
    }

    /**
     * @return pickup timestamp
     */
    public LocalDateTime getPickedAt() {
        return pickedAt;
    }


    /**
     * @param pickedAt pickup timestamp
     */
    public void setPickedAt(LocalDateTime pickedAt) {
        this.pickedAt = pickedAt;
    }

    /**
     * @return cancellation timestamp
     */
    public LocalDateTime getCancelledAt() {
        return cancelledAt;
    }


    /**
     * @param cancelledAt cancellation timestamp
     */
    public void setCancelledAt(LocalDateTime cancelledAt) {
        this.cancelledAt = cancelledAt;
    }
}
