package com.delivery.dvApp.entity;

import com.delivery.dvApp.enums.Category;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
/**
 * Entity representing a Restaurant in the system.
 *
 * <p>
 * This class is mapped to a database table via JPA and stores
 * basic restaurant information such as name, address, phone number,
 * and category.
 * </p>
 *
 * <p>
 * The entity also supports soft deletion using the {@code deleted} flag.
 * Instead of physically removing a record from the database,
 * the record can be marked as deleted.
 * </p>
 */
@Entity
public class Restaurant {
    /**
     * Unique identifier of the restaurant.
     * <p>
     * Auto-generated by the database using IDENTITY strategy.
     * This field is read-only in JSON responses.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private Long id;

    /**
     * Name of the restaurant.
     */
    private String name;

    /**
     * Physical address of the restaurant.
     */
    private String address;



    /**
     * Contact phone number of the restaurant.
     */
    private String phoneNumber;

    /**
     * Category of the restaurant (e.g., FAST_FOOD, ITALIAN, CHINESE).
     *
     * <p>
     * Stored as a String value in the database.
     * This field cannot be null.
     * </p>
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Category category;


    /**
     * Soft delete flag.
     *
     * <p>
     * When set to true, the restaurant is considered deleted
     * but remains in the database.
     * This field is read-only in JSON.
     * </p>
     */
    @Column(nullable = false)
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private boolean deleted = false;

    /**
     * Default constructor required by JPA.
     */
    public Restaurant() {
    }

    /**
     * Constructor for creating a new Restaurant.
     *
     * @param name        restaurant name
     * @param address     restaurant address
     * @param phoneNumber restaurant phone number
     * @param category    restaurant category
     */
    public Restaurant(String name, String address,String phoneNumber,Category category) {
        this.name = name;
        this.address = address;
        this.phoneNumber = phoneNumber;
        this.category = category;
    }

    /**
     * @return restaurant ID
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id restaurant ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return restaurant name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name restaurant name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return restaurant address
     */
    public String getAddress() {
        return address;
    }

    /**
     * @param address restaurant address
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * @return restaurant phone number
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * @param phoneNumber restaurant phone number
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }


    /**
     * @return restaurant category
     */
    public Category getCategory() {
        return category;
    }

    /**
     * @param category restaurant category
     */
    public void setCategory(Category category) {
        this.category = category;
    }

    /**
     * @return true if restaurant is soft-deleted, false otherwise
     */
    public boolean isDeleted() {
        return deleted;
    }

    /**
     * @param deleted soft delete flag
     */
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }
}
